### PR TITLE
[type:fix]fix SofaServiceEventListenerTest.testBuildMetaDataDTO

### PR DESCRIPTION
**Pull request by tian-pengfei**
Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

I think the `SofaServiceEventListenerTest.testBuildMetaDataDTO` method has a problem.

Sometimes the expected one's timeMillis is diffrent from the actual's ,Because of the difference of creation time

image

5cf5a5971672a56fcf3cd68a29f71c2

image

image

So, Removes comparing timeMillis  in MetaDataRegisterDTO#equals

### CODE REVIEW

**Review by dragon-zhang — APPROVED** [review]
LGTM

**Review by dragon-zhang — CHANGES_REQUESTED** [review]
the `equals` maybe also need changes, too ?

**Comment by tian-pengfei** [comment]
> the `equals` maybe also need changes, too ?

That depends on whether comparing two objects to be equal should take into account the time they was created

**Comment by tian-pengfei** [comment]
> the `hashCode` maybe also need changes, too ?

yes I will fix it

**Review by dragon-zhang — APPROVED** [review]

**Pull request merged**
