### PR TITLE
[ISSUE #3852] bug fix , request plugin can't replaceCookie 

### LINKED ISSUE #3870: [BUG] <title> Request plugin can't replaceCookie
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image
Request plugin add new Rule to ReplaceCookie，But can't do it。

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
ShenYu version(s):
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JairoSun**
Fixes #3870
- fix request plugin can't replaceCookie bug
- add test case for request plugin ensure the replacement cookie rules meet expectations
Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by qizhq** [comment]
replaceCookie is replace cookie's name,but now is replace value;

private void replaceCookieKey(final Map.Entry<String, String> shenyuCookie, final MultiValueMap<String, HttpCookie> cookies) {
        List<HttpCookie> httpCookies = cookies.get(shenyuCookie.getKey());
        if (Objects.nonNull(httpCookies)) {
            List<HttpCookie> newCookies = httpCookies.stream().map(cookie ->
                    new HttpCookie(shenyuCookie.getValue(), cookie.getValue()))
                    .collect(Collectors.toList());
            cookies.remove(shenyuCookie.getKey());
            cookies.addAll(shenyuCookie.getValue(), newCookies);
        }
    }

**Comment by JairoSun** [comment]
> replaceCookie is replace cookie's name,but now is replace value;
> 
> private void replaceCookieKey(final Map.Entry<String, String> shenyuCookie, final MultiValueMap<String, HttpCookie> cookies) { List httpCookies = cookies.get(shenyuCookie.getKey()); if (Objects.nonNull(httpCookies)) { List newCookies = httpCookies.stream().map(cookie -> new HttpCookie(shenyuCookie.getValue(), cookie.getValue())) .collect(Collectors.toList()); cookies.remove(shenyuCookie.getKey()); cookies.addAll(shenyuCookie.getValue(), newCookies); } }

Sorry, I misunderstood the function of this rule. I'll fix it tonight

**Comment by yu199195** [comment]
hi，pls check ci

**Comment by JairoSun** [comment]
> hi，pls check ci
@yu199195 @qizhq 
hi，i modified the code and passed the check-style and test case locally. pls make a code review when you have time

**Comment by yu199195** [comment]
> hi，i modified the code and passed the check-style and test case locally. pls make a code review when you have time

Thanks， CI is running

**Review by yu199195 — APPROVED** [review]

**Pull request merged**
