### PR TITLE
[Improve]Test case optimization(#5743)

### PR DESCRIPTION
**Pull request by po-168**
[Improve]Test case optimization(#5743)

### CODE REVIEW

**Comment by po-168** [comment]
@Aias00 Please review code PR

**Comment by Aias00** [comment]
> @Aias00 Please review code PR

hi, at least u should make the ci success

**Comment by po-168** [comment]
> > @Aias00 Please review code PR
> 
> hi, at least u should make the ci success

Local verification is successful. I don’t know why. Can you give me some help? I want to solve this PR as soon as possible.

**Comment by Aias00** [comment]
> > > @Aias00 Please review code PR
> > 
> > 
> > hi, at least u should make the ci success
> 
> Local verification is successful. I don’t know why. Can you give me some help? I want to solve this PR as soon as possible.

hi，the error shows ur checkstyle not passed，when u coding local，u should make mvn checkstyle passed

**Comment by po-168** [comment]
> > > > @Aias00 Please review code PR
> > > 
> > > 
> > > hi, at least u should make the ci success
> > 
> > 
> > Local verification is successful. I don’t know why. Can you give me some help? I want to solve this PR as soon as possible.
> 
> hi，the error shows ur checkstyle not passed，when u coding local，u should make mvn checkstyle passed
Hi，TKS, According to your instructions, I have resolved the issue, but I have created a new PR(#5745) that I have already closed.

**Pull request closed without merging**
