### PR TITLE
Enable Maven parallel build in GitHub Actions

### PR DESCRIPTION
**Pull request by TeslaCN**
Speed up GitHub Actions

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by damonxue** [comment]
image
maybe set threadSafe is first in need.

**Comment by TeslaCN** [comment]
The windows is still slow.

**Comment by TeslaCN** [comment]
> image
> maybe set threadSafe is first in need.

The warning can be ignored. Bump rat to 0.15 can eliminate the warning.

**Comment by TeslaCN** [comment]
Close it for now due to slow Windows.

**Pull request closed without merging**
