### PR TITLE
[type:feature] added expression and replaced some grammar of ${} with expression 

### PR DESCRIPTION
**Pull request by tian-pengfei**
Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

SpEL Is powerful funtion , I think mock should support it.
```java
 @Test
    public void testGenerate() {

        generator.parseRule("expression|T(java.time.LocalDate).now()");
        assertThat(generator.generate(), is(LocalDate.now().toString()));

        generator.parseRule("expression|T(org.apache.shenyu.plugin.mock.util.RandomUtil).randomInt(1,100)");
        assertThat(Integer.valueOf(generator.generate()),
                is(Matchers.allOf(greaterThanOrEqualTo(1), lessThanOrEqualTo(100))));
    }
```
I have two other ideas

1.   other generators' function could be added to this generator, which means we can remove other generators   (implemented)
   eg:
```java
 generator.parseRule("expression|#randomInt(1,100)");
```
2. if generator could get request content,the response can be associated with the request .
  eg:
```java
generator.parseRule("expression|request.headers['jwt']");
generator.parseRule("expression|request.content.username");
```

### CODE REVIEW

**Comment by tian-pengfei** [comment]
implement the first idea

<html>
<body>
<!DOCTYPE html><figure class="md-table-fig" cid="n117" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

before | now
-- | --
${int\|min-max} | ${expression\|#int(min,max)}
${double\|min-max\|format} | ${expression\|#double(min,max)}
${email} | ${expression\|#email()}
${phone} | ${expression\|#phone()}
${zh\|min-max} | ${expression\|#zh(min,max)}
${en\|min-max} | ${expression\|#en(min,max)}
${list\|[arg1,arg2...]} | ${expression\|#oneOf(arg1,agr2...)}
${current\|format} | ${expression\|#current(format)}
${bool} | ${expression\|#bool()}

</figure><br class="Apple-interchange-newline">
</body>
</html>

**Comment by yu199195** [comment]
can you update sql file？

**Comment by tian-pengfei** [comment]
> can you update sql file？

No problem

**Comment by tian-pengfei** [comment]
> can you update sql file？

Sorry ,I  dont know what I need to update in sql file.

**Comment by LiuTianyou** [comment]
> tian-pengfei
Only the format and generation logic of random data expressions have been modified, so no SQL files need to be modified

**Review by li-keguo — APPROVED** [review]

**Pull request merged**
