### PR TITLE
[ISSUE #3157] Optimize admin  dto validate.

### LINKED ISSUE #3157: [Volunteer] admin data validate
### Volunteer help

validate the admin submit data with annotation at the DTO, like the length of the data.

### PR DESCRIPTION
**Pull request by Lifeng-Lv**
Fixes #3157 

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by moremind** [comment]
pls check ci

**Comment by Lifeng-Lv** [comment]
@moremind Hi, check completed. the ci task is gone, whether forced push cause the workflow reset?

**Comment by moremind** [comment]
maybe you can change more code about dto?

**Comment by Lifeng-Lv** [comment]
maybe I have finished. :-)

**Review by yu199195 — APPROVED** [review]

**Pull request merged**
