### PR TITLE
sync frontend

### PR DESCRIPTION
**Pull request by kerwin612**
sync frontend:
apache/shenyu-dashboard#392
apache/shenyu-dashboard#396
apache/shenyu-dashboard#397
apache/shenyu-dashboard#398
apache/shenyu-dashboard#399
apache/shenyu-dashboard#401

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by moremind** [comment]
may need to waiting merge shenyu-dashboard

**Comment by moremind** [comment]
you should build from master branch when merged

**Comment by kerwin612** [comment]
The dashboard pr I listed was merged into master when I submitted this pr, and this pr submission was built from master.

**Comment by kerwin612** [comment]
The dashboard pr I listed was merged into master when I submitted this pr, and this pr submission was built from master.

**Comment by kerwin612** [comment]
Repush artifacts built on the latest master branch;  
Append the following two PRs (merged into master):  
apache/shenyu-dashboard#400
apache/shenyu-dashboard#405

**Review by moremind — APPROVED** [review]

**Pull request merged**
