### PR TITLE
Remove Alibaba Dubbo Support #5498

### PR DESCRIPTION
**Pull request by Aias00**
Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by tomsun28** [comment]
hi, there are some `alibaba dubbo` test script in `.github/workflows`

**Comment by Aias00** [comment]
got it，still working on

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/19/2024 09:02 |
| To | apache/shenyu ***@***.***> |
| Cc | aias00 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [apache/shenyu] Remove Alibaba Dubbo Support #5498 (PR #5500) |

hi, there are some alibaba dubbo test script in .github/workflows

**Comment by Aias00** [comment]
> hi, there are some `alibaba dubbo` test script in `.github/workflows`

review this, pls

**Review by tomsun28 — APPROVED** [review]
LGTM!👍👍 Local test and action test passed.

**Comment by tomsun28** [comment]
link #5374

**Pull request merged**
