### PR TITLE
[type:fix] fix admin: show the dictCode

### LINKED ISSUE #5373: [Task] Add dictionary code column to dictionary table
### Description

image

### Task List

1. Add the `Dictionary code` column to VO
2. Upgrade the frontend to show the result
3. Use `like` instead of `=` to query the dictionary

### PR DESCRIPTION
**Pull request by MRgenial**
Fixes #5373 

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by moremind** [comment]
pls check ci

**Comment by moremind** [comment]
I think you should update shenyu-dashboard

**Comment by MRgenial** [comment]
shenyu-dashboard is updated,you can see it.

**Comment by moremind** [comment]
LGTM

**Review by moremind — APPROVED** [review]

**Pull request merged**
