### PR TITLE
Fix 4357: Optimize logs for shenyu-admin

### PR DESCRIPTION
**Pull request by balloon72**
Optimize logs for shenyu-admin

### CODE REVIEW

**Comment by KevinClair** [comment]
`LOG.error("duplicate key exception {}", exception.getMessage());` can not print stackTrace.

**Comment by yu199195** [comment]
pls resolved conflicts

**Comment by balloon72** [comment]
> `LOG.error("duplicate key exception {}", exception.getMessage());` can not print stackTrace.

Modified

**Comment by balloon72** [comment]
> pls resolved conflicts

Resolved

**Comment by KevinClair** [comment]
what about others?

**Pull request closed without merging**
