### PR TITLE
[ISSUE #3805] Add convenience annotation for tars

### PR DESCRIPTION
**Pull request by hezean**
Subtask of #3805

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by HeZean** [comment]
Hi, I think I'm getting some trouble that I've searched but cannot resolve without submitting another PR to TarsJava.

In [Tars's SpringBootAppContext.class](https://github.com/TarsCloud/TarsJava/blob/7550e165cd4a67637c333a21f99fbb7e169ca27d/spring/tars-spring-boot-starter/src/main/java/com/qq/tars/server/apps/SpringBootAppContext.java#L96), it uses `AnnotationUtils#getAnnotation` to get the `TarsServant` annotation, which will return `TarsServant{name = "", value = ""}` instead the one with aliased value. It should be changed to use `AnnotatedElementUtils#findMergedAnnotation`, this won't break its original capability.

Should I submit a PR to TarsJava first? Any suggestions?

**Comment by dragon-zhang** [comment]
> Hi, I think I'm getting some trouble that I've searched but cannot resolve without submitting another PR to TarsJava.
> 
> In [Tars's SpringBootAppContext.class](https://github.com/TarsCloud/TarsJava/blob/7550e165cd4a67637c333a21f99fbb7e169ca27d/spring/tars-spring-boot-starter/src/main/java/com/qq/tars/server/apps/SpringBootAppContext.java#L96), it uses `AnnotationUtils#getAnnotation` to get the `TarsServant` annotation, which will return `TarsServant{name = "", value = ""}` instead the one with aliased value. It should be changed to use `AnnotatedElementUtils#findMergedAnnotation`, this won't break its original capability.
> 
> Should I submit a PR to TarsJava first? Any suggestions?

I think so. Don't hesitate to submit PR to `tars`.

**Comment by dragon-zhang** [comment]
@HeZean please add wechat Z18179469818

**Comment by dragon-zhang** [comment]
@HeZean TarsJava `1.7.3` has released, you can continue.

**Comment by yu199195** [comment]
too long time ，it be close.

**Pull request closed without merging**
