### PR TITLE
[type:test][ISSUE #4540] add plugin test cases for admin

### PR DESCRIPTION
**Pull request by whenelse**
[type:test][ISSUE #4540] add plugin test cases for admin.([#4540 ](https://github.com/apache/shenyu/issues/4540))

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by yu199195** [comment]
hi，pls check ci

**Comment by whenelse** [comment]
@moremind I found a code error in PluginHandleChangedEvent. The dataType in the contrast() method takes the dateCreated field of before.[PluginHandleChangedEvent ](https://github.com/apache/shenyu/blob/master/shenyu-admin/src/main/java/org/apache/shenyu/admin/model/event/handle/PluginHandleChangedEvent.java)

**Comment by moremind** [comment]
> @moremind I found a code error in PluginHandleChangedEvent. The dataType in the contrast() method takes the dateCreated field of before.[PluginHandleChangedEvent ](https://github.com/apache/shenyu/blob/master/shenyu-admin/src/main/java/org/apache/shenyu/admin/model/event/handle/PluginHandleChangedEvent.java)

can you fix it in another pr？

**Comment by whenelse** [comment]
> > @moremind I found a code error in PluginHandleChangedEvent. The dataType in the contrast() method takes the dateCreated field of before.[PluginHandleChangedEvent ](https://github.com/apache/shenyu/blob/master/shenyu-admin/src/main/java/org/apache/shenyu/admin/model/event/handle/PluginHandleChangedEvent.java)
> 
> can you fix it in another pr？

of course!

**Comment by moremind** [comment]
pls add my wechat: yijia1949

**Review by moremind — APPROVED** [review]

**Pull request merged**
