### PR TITLE
shenyu-client-motan test case

### PR DESCRIPTION
**Pull request by Divyansh200102**
#4546

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by dragon-zhang** [comment]
@Divyansh200102 please add wechat Z18179469818

**Review by dragon-zhang — APPROVED** [review]

**Comment by Divyansh200102** [comment]
> @Divyansh200102 please add wechat Z18179469818

@dragon-zhang is there any way to get in contact?

**Comment by dragon-zhang** [comment]
> > @Divyansh200102 please add wechat Z18179469818
> 
> @dragon-zhang is there any way to get in contact?

Sorry, no, contributors are all in the wechat.

**Comment by Divyansh200102** [comment]
> > > @Divyansh200102 please add wechat Z18179469818
> > 
> > 
> > @dragon-zhang is there any way to get in contact?
> 
> Sorry, no, contributors are all in the wechat.

@dragon-zhang Do you use whatsapp ? The problem is that wechat is banned in my country so I cannot access it that's why I am asking for alternatives...

**Pull request merged**
