### PR TITLE
[ISSUE #3713][resolved #3774] Add new plugin: basic-auth

### PR DESCRIPTION
**Pull request by kerwin612**
Continue to finish #3774  

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by moremind** [comment]
pls check sql

**Comment by kerwin612** [comment]
> pls check sql

The latest scripts in my local mysql8 container under the execution of no problem, but CI or did not pass, I do not see the specific reasons here;

**Comment by kerwin612** [comment]
> pls check sql

All checks have passed :)

**Review by moremind — CHANGES_REQUESTED** [review]

**Comment by moremind** [comment]
pls add integrated test for basic-auth plugin

**Comment by kerwin612** [comment]
> pls add integrated test for basic-auth plugin

* [shenyu-plugin-basic-auth/src/test](https://github.com/apache/shenyu/pull/5258/files#diff-b4982601fe8a05111c0893b5fa13f30ec7b4e7cd8aef0a1d110d8ce0fa99cdb1)
* [BasicAuthPluginTest](https://github.com/apache/shenyu/pull/5258/files#diff-b4982601fe8a05111c0893b5fa13f30ec7b4e7cd8aef0a1d110d8ce0fa99cdb1R74)

Aren't these tests enough?

**Comment by moremind** [comment]
shenyu-integrated-test

**Review by moremind — APPROVED** [review]

**Pull request merged**
