### PR TITLE
feat(dubbo): support dubbo3 tri protocol

### PR DESCRIPTION
**Pull request by fantiq**
support dubbo3 `tri` and `dubbo` protocol

i add a field on `rpcExt`, on client write the dubbo protocol in the metadata. on shunyu gateway, create reference by the metadata rpcExt protocol.

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by JooKS-me** [comment]
A good job.
Pls check the ci, there are some style error.
image

**Comment by fantiq** [comment]
> A good job. Pls check the ci, there are some style error. image

fixed

**Comment by JooKS-me** [comment]
still 2 style error
image

**Comment by fantiq** [comment]
> still 2 style error image

fixed

**Review by JooKS-me — CHANGES_REQUESTED** [review]
https://github.com/apache/shenyu/blob/0eab567886b6c8eb67f3214e6438cb1b7f1e3b5d/shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml#L61-L91

Please change the dependencies to 

```xml
<dependency>
            <groupId>org.apache.shenyu</groupId>
            <artifactId>shenyu-spring-boot-starter-plugin-apache-dubbo</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>3.1.1</version>
            <type>pom</type>
        </dependency>
```

**Review by JooKS-me — APPROVED** [review]
LGTM

**Pull request merged**
