### PR TITLE
Add test case for `ShenyuClientRegisterEventPublisher`

### PR DESCRIPTION
**Pull request by Divyansh200102**
Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by Divyansh200102** [comment]
@dragon-zhang @moremind I have no idea why the checks are failing the tests are working perfectly fine on my local system tell me how do i resolve this?
image

**Comment by Divyansh200102** [comment]
@dragon-zhang @moremind I have no idea why the checks are failing the tests are working fine in my local system please help me resolve this.
image

**Comment by moremind** [comment]
looks good, but you should add `public` for the test method and check the code

**Comment by Divyansh200102** [comment]
> looks good, but you should add `public` for the test method and check the code

I did as said but still it's not working @moremind .I am not able to figure out what's going wrong?

**Comment by moremind** [comment]
Error:  src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java:[60] (whitespace) EmptyLineSeparator: 'METHOD_DEF' should be separated from previous statement.
Error:  src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java:[60,5] (javadoc) JavadocMethod: Missing a Javadoc comment.
Error:  src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java:[68] (whitespace) EmptyLineSeparator: 'METHOD_DEF' should be separated from previous statement.
Error:  src/test/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientRegisterEventPublisherTest.java:[33] (whitespace) EmptyLineSeparator: 'VARIABLE_DEF' should be separated from previous statement.

**Comment by Divyansh200102** [comment]
> ```
> Error:  src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java:[60] (whitespace) EmptyLineSeparator: 'METHOD_DEF' should be separated from previous statement.
> Error:  src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java:[60,5] (javadoc) JavadocMethod: Missing a Javadoc comment.
> Error:  src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java:[68] (whitespace) EmptyLineSeparator: 'METHOD_DEF' should be separated from previous statement.
> Error:  src/test/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientRegisterEventPublisherTest.java:[33] (whitespace) EmptyLineSeparator: 'VARIABLE_DEF' should be separated from previous statement.
> ```

If you don't mind could you tell how did you find these errors? @moremind

**Review by moremind — APPROVED** [review]

**Pull request merged**
