### PR TITLE
Fix the issue with deleting the "Host" header

### PR DESCRIPTION
**Pull request by titxue**
#5780

### CODE REVIEW

**Comment by yu199195** [comment]
why delete 'Host'  from  http header

**Comment by titxue** [comment]
> why delete 'Host' from http header

**Comment by titxue** [comment]
> why delete 'Host' from http header

The original logic ends up removing the ‘Host’ header, which causes any custom ‘Host’ header functionality in the request plugin to fail. My recommendation is to remove the code that deletes ‘Host’ to allow the plugin to function correctly, increasing flexibility without forcing the removal of the ‘Host’ header. Alternatively, this could be made configurable, either in the request setup or the service discovery. In any case, forcing the deletion of ‘Host’ in code is not ideal. Please also refer to the details in my submitted issue for further clarification.

**Review by titxue — COMMENTED** [review]
Remove the delete host operation

**Comment by moremind** [comment]
not right

**Pull request closed without merging**
