### PR TITLE
[ISSUE #4475] Modify memory leak error

### LINKED ISSUE #4475: [BUG] <may MemorySafeWindowTinyLFUMap cause a memory leak>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
memory leaked

### Expected Behavior
when i use System.gc(), no memory leaked

### Steps To Reproduce

public class TestMemoryLeak {
    // 1m内存
    private static final int M_1 = 1 * 1024 * 1024;

    public static void main(String[] args) throws InterruptedException, IOException {
        System.in.read();
        try {
            mswtMapTest();
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.gc();
        TimeUnit.SECONDS.sleep(Long.MAX_VALUE);
    }

    public static void mswtMapTest() {
        for (int i = 0; i < 10; i++) {
            System.gc();
            MemorySafeWindowTinyLFUMap<String, Byte[]> map = new MemorySafeWindowTinyLFUMap<>(1, 100);
            map.put(String.valueOf(i), new Byte[M_1 * 2]);
            // 手动GC
        }
    }

    public static void commonMapTest() {
        for (int i = 0; i < 10; i++) {
            System.gc();
            Map<String, Byte[]> map = new HashMap<>();
            map.put(String.valueOf(i), new Byte[M_1 * 2]);
            // 手动GC
            System.gc();
        }
    }
}

### Environment
jvm：  -Xms20m -Xmx20m
```markdown
ShenYu version(s):
```

### Debug logs

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.apache.shenyu.common.cache.TestMemoryLeak.mswtMapTest(TestMemoryLeak.java:44)
	at org.apache.shenyu.common.cache.TestMemoryLeak.main(TestMemoryLeak.java:32)

### Anything else?

MemorySafeWindowTinyLFUMap  hold a static reference ALL, every reference of MemorySafeWindowTinyLFUMap will be always hold by the reference, and may cause a memory leak

### PR DESCRIPTION
**Pull request by xuyicheng1995**
Fixes #4475 : Modify MemorySafeWindowTinyLFUMap memory leak error.

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by xuyicheng1995** [comment]
> this is not right.

why? i have tested, before modified, my application throw oom, and after modified,  i works normally

**Comment by xuyicheng1995** [comment]
> maybe you can refer to: #4486

i have no idea about your commited code,  if it is convenient, can we add WeChat?

**Comment by moremind** [comment]
> > maybe you can refer to: #4486
> 
> i have no idea about your commited code, if it is convenient, can we add WeChat?

my wechat is: yijia1949

**Comment by yu199195** [comment]
Hi， this pr can close？

**Comment by yu199195** [comment]
@xuyicheng1995 i think https://github.com/apache/shenyu/pull/4486 already fix it

**Pull request closed without merging**
