### PR TITLE
Add test case for `ShenyuClientMetadataExecutorSubscriber`

### PR DESCRIPTION
**Pull request by Divyansh200102**
#4544

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by Divyansh200102** [comment]
@moremind @dragon-zhang I have no idea why the checks are failing all the tests are working perfectly in my local system...?

**Comment by Divyansh200102** [comment]
@moremind @dragon-zhang I have no idea why the checks are failing the tests are working perfectly in my local system..??

**Comment by moremind** [comment]
pls check ci, pls add `final`

**Comment by Divyansh200102** [comment]
Please review the pr @moremind

**Review by dragon-zhang — APPROVED** [review]

**Pull request merged**
